---
Title: HXPM
About: |
  Truly one of the worst project management solutions of all time, do not use. This is alpha quality software, you'll know it's ready to try when there's actual documentation.
# Adapter: fs # or 'git' in the future
# AdapterConfig:
#   Path: ./projects
