---
title: Hexylena's Project Management Tool
about: |
  <b style="color:red">DROP AND RUN</b><br><br>DO NOT USE.

# adapter: fs # or 'git' in the future
# AdapterConfig:
#   Path: ./projects
ExportUseGoogleFonts: true
ExportPrefix: /project-management/
ServerBindHost: "0.0.0.0"
ServerBindPort: "8080"
ServerBindTailscale: false

QueryChildren: |
  SELECT
    title, created, Author
  FROM notes
  WHERE parent = 'NOTE_ID'
    AND type != 'log'
  GROUP BY type
  ORDER BY Status, created
QueryChildrenLayout: table
QueryHomepage: |
  SELECT
      title, created, modified
  FROM NOTES
  WHERE
    parent is null
  GROUP BY type
  ORDER BY created
QueryHomepageLayout: table
