---
title: Hexylena's Project Management Tool
about: |
  DROP AND RUN

  DO NOT USE.

# adapter: fs # or 'git' in the future
# AdapterConfig:
#   Path: ./projects
ExportUseGoogleFonts: true
ExportPrefix: /project-management/
ServerBindAddr: "0.0.0.0:3333"

QueryChildren: |
  SELECT
    title, created, Author
  FROM notes
  WHERE parent = 'NOTE_ID'
    AND type != 'log'
  GROUP BY type
  ORDER BY Status, created
QueryChildrenLayout: table
QueryHomepage: |
  SELECT
      title, created, modified
  FROM NOTES
  WHERE
    parent is null
  GROUP BY type
  ORDER BY created
QueryHomepageLayout: table
