services:
  web:
    restart: unless-stopped
    build: .
    volumes:
      - "${PWD}:/code/"
      - "${PWD}/repos:/repos"
      - "/root/.ssh/:/root/.ssh/"
      - "/root/.gitconfig:/root/.gitconfig"
    env_file: "prod.env"
    network_mode: service:ts
    depends_on:
      - ts

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    environment:
      IMGPROXY_BASE_URL: "http://localhost:8000/file/blob/"
      IMGPROXY_PATH_PREFIX: "/imgproxy"
      IMGPROXY_KEEP_ALIVE_TIMEOUT: 30
      IMGPROXY_DOWNLOAD_TIMEOUT: 10
      IMGPROXY_ALLOW_LOOPBACK_SOURCE_ADDRESSES: true
    restart: unless-stopped
    network_mode: service:ts
    depends_on:
      - ts

  ts:
    image: tailscale/tailscale:v1.76
    hostname: penemure 
    env_file: "prod.env"
    volumes:
      - ${PWD}/ts/state:/var/lib/tailscale
      - ${PWD}/ts/config/config.json:/config/config.json
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  #cron:
  #  restart: always
  #  build: .
  #  command: |
  #    bash -c "while true; do curl http://web:8000/sync; sleep 600; done;"
  #  links:
  #    - web:web
