services:
  web:
    restart: always
    build: .
    environment:
    volumes:
      - "${PWD}:/code/"
      - "${PWD}/repos:/repos"
      - "/root/.ssh/:/root/.ssh/"
      - "/root/.gitconfig:/root/.gitconfig"
    ports:
      - 8484:8000
    env_file: "prod.env"
  cron:
    restart: always
    build: .
    command: |
      bash -c "while true; do curl http://web:8000/sync; sleep 600; done;"
    links:
      - web:web

  ts:
    image: tailscale/tailscale:v1.76
    container_name: ts-hxpm
    hostname: hxpm
    environment:
    env_file: "prod.env"
    volumes:
      - ${PWD}/ts/state:/var/lib/tailscale
      - ${PWD}/ts/config/config.json:/config/config.json
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
