name: Forgejo deploy

on:
  # Runs on pushes targeting the default branch
  push:

jobs:
  setup:
    runs-on: docker
    container:
       image: catthehacker/ubuntu:act-latest
    steps:
      - run: |
          git lfs env
          env | sort

      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - run: |
          git lfs env 
          env | sort

      # BEGIN Dependencies
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Deps
        run: |
          pip install -r requirements.txt
          pip install awscli
      # END Dependencies

      - name: Export example site
        run: python scripts/export.py pub -f html -p penemure -s https://s3.chimera-pumpkinseed.ts.net

      - name: Export site
        run: |
          aws s3 cp --recursive _build/ s3://penemure/
        env:
          URL: ${{ secrets.URL }}
          TOKEN: ${{ secrets.TOKEN }}
          AWS_ENDPOINT_URL: http://192.168.2.12:9000
          AWS_ACCESS_KEY_ID: linkwarden2rss
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
